### ISSUE TITLE
[Feature request] Option to change the color of the gesture line

### ISSUE THREAD

**Issue by ryanbuening** [lrydzkowski/SimpleMouseGestures#2]
It would be nice to have the option to change the color of the gesture. It is sometimes difficult to see the black line when browsing sites that are darker.

**Comment by lrydzkowski** [comment]
I will add it to the next version :)

**Comment by lrydzkowski** [comment]
It's ready. In the version 0.3.3 there is the ability to change settings:
- line color,
- line width.

![image](https://github.com/lrydzkowski/SimpleMouseGestures/assets/1909426/ab2042a3-060d-4358-aa79-cea9282446f1)

**Comment by ryanbuening** [comment]
Nice!
